ntpeters/vim-better-whitespace

README.md, plugin/better-whitespace.vim
This PR enables per buffer enable/disable/toggle of whitespace highlighting, by wrapping the actual syntax highlighting in functions that check a buffer-local variable before highlighting. This variable (`b:better_whitespace_enabled`) is set to a sensible default, guessed from the blacklist and updated if the file type changes.
The global `g:better_whitespace_enabled` still exists and completely disables whitespace highlighting if it is set to `0`.
Including the initial un/redraw from Enable/Disable inside `SetupAutoCommands` and twiddling with the choice of events that trigger the setup allows to fix various bugs, at least for me with vim 7.4 (2013 Aug 10).
PS: Sorry for the noise on the issues, I managed to forget one of your commits and had to force-push.
=> Per-buffer whitespace

plugin/better-whitespace.vim
See issue #45
To resolve this i've changed the hook to be for both BufEnter and WinEnter. Let me know if there's anything further I can do around this!
=> Highlight whitespace on both BufEnter and WinEnter for e.g. split

plugin/better-whitespace.vim
Fixes #51.
Markdown files depend on trailing whitespace.
=> Add markdown to default blacklist

README.md, plugin/better-whitespace.vim
This adds `EnableStripWhitespaceOnSave` and
`DisableStripWhitespaceOnSave` functions as an alternative for
`ToggleStripWhitespaceOnSave`.
Using these you can (correctly) set the variables for the buffer to
allow the toggle to work.  I updated the readme to reflect this change.
Closes #54
=> Added explicit Enable/Disable for strip-on-save

plugin/better-whitespace.vim
4 spaces were used everyplace else, but this one line used 2.
=> Inconsistent indentation

plugin/better-whitespace.vim
Before this commit, `g:better_whitespace_operator` was checked for
non-emptiness as a string which was always true. As a result, the
whitespace operator could not be disabled.
=> Fixed check for empty better-whitespace-operator key

README.md, doc/better-whitespace.txt, plugin/better-whitespace.vim
This change updates the default operator mapping to `<leader>s`, and
adds a check to ensure the mapping does not already exist.
Fixes #78
=> Update operator default to <leader>s

plugin/better-whitespace.vim
With config:
```
let g:better_whitespace_enabled = 0
let g:strip_whitespace_on_save = 1
let g:better_whitespace_filetypes_blacklist=['diff', 'gitcommit', 'unite', 'qf', 'help']
```
when I open some file without recognized filetype (for example: `touch a; vim a`) I get:
```
"a" 0L, 0C                                                                                                                                                                                
Error detected while processing function <SNR>63_SetupAutoCommands[37]..<SNR>63_ShouldStripWhitespace:                                                                                    
line    3: …
```
=> Fix for 'Undefined variable' err when no FileType

plugin/better-whitespace.vim
Enable/Disable of highlighting modelled after the enabling/disabling of whitespace stripping.
=> This should hopefully be the last of "undefined variable" errors

README.md, plugin/better-whitespace.vim
I think it would be very self-contained and tidy if we can have all the features or configurations of the plugin to be configured by simply setting the corresponding global variables (This patch won't break anybody's configuration if they have already set the highlight group in their vimrc)
=> Add a configurable variable to set the highlight color of trailing whitespace

README.md, doc/better-whitespace.txt, plugin/better-whitespace.vim
Includes
- Fixes for open bugs 
- #111 avoid aliases when looking up diff command
- 98bf95e remove unwanted errors in fallback `trim()` function
- README clarifications
- #119 typo on using modified lines
- #115 explain disabling functionality rather than disabling plugin
- Better practices:
- for match groups: c10c09c using `matchadd()` instead of `:match`
- for detection of the `trim()` function: 2f9aa7b  use  `exists()` rather than checking version number
=> Pull all recent updates

plugin/better-whitespace.vim
Stripping EOF whitespace does not work outside of Unix formats. The pattern only needs the `\n` alone as it will match new lines on all file formats regardless of the actual `<EOL>` value written to the file.
Previously only stripping on Unix, now tested and working correctly on all formats after patch.
=> Fix EOF whitespace strip

plugin/better-whitespace.vim
Have CleanLinks be disabled by default in popups, and fix #128 where the highlighting disappears on popup closing.
=> Handle new buffer types: popups

plugin/better-whitespace.vim
- Fixes blacklisting of help, fugitive, etc. filetypes which are set
with a delay (fixes #108 #137)
- Blacklisting of empty buffers is possible by adding "" to the blacklist (fixes #130)
- Maintains priority of manually set highlighting (with commands
:Disable :Enable :Toggle) over FileType autodection, in particular for
when preferences are set with autocommands.
- Disable by default for all non-writable buffer types (fixes #125). Could be
improved if there are events on buftype change (?)
=> Rework FileType detection

README.md, doc/better-whitespace.txt, plugin/better-whitespace.vim
Git diffs routinely contain trailing whitespace. The excess highlights
are rather distracting.
=> Add git to default blacklist

plugin/better-whitespace.vim
Fixed an infinte loop in RestoreSearchHistory when the index parameter is equal to -1. This happens when vim is started for the very first time.
=> Fix Infinte loop in RestoreSearchHistory

plugin/better-whitespace.vim
Previously on saving, whitelines at eof are only removed if whitespace
exists - as the confirmation is only asked for when whitespace in the
specified ranges is detected, and by default whitespace and whitelines
are not removed unless a confirmation is approved.
Therefore, a function was created to detect whitelines. The funciton is
called when no whitespace is found and strip_whitelines_at_eof is set.
If whitelines are found, the user is asked for confirmation and the
whitelines are removed.
=> Detect whitelines on save if specified

plugin/better-whitespace.vim
Triggers our detection again when the `term` buftype is set − different events in vim and neovim.
=> Nvim term fix

plugin/better-whitespace.vim
In #161, a non-Neovim fallback for terminal detection used the TerminalWinOpen event. This event was added in Vim 8.1.2219 (Oct 26, 2019), and is causing previous versions to complain at startup:
```
Error detected while processing /home/jbylsma/.vim/plugged/vim-better-whitespace/plugin/better-whitespace.vim:
line  394:
E216: No such group or event: TerminalWinOpen * call <SID>SetupAutoCommands()
Press ENTER or type command to continue
```
I'm noticing this on RHEL8.9 servers. Adding an "else if" check quiets the error.
=> Ignore TerminalWinOpen event when not supported

plugin/better-whitespace.vim
fixes issue #127 (and possibly others)
=> make autocmds for whitespace highlights/deletions buffer-specific
